main: com.minegusta.mggames.main.Main
name: MGGames
author: janie177
version: ${project.version}
commands:
   vote:
      description: Vote for a map.
      usage: /vote
   game:
      description: Admin commands for setting data.
      usage: /game
   join:
      usage: /Join <Game>
      description: Join a given game.
   leave:
      usage: /Leave
      description: Leave your current game.
      aliases: [exit, quit, hub, abort, screwyouguysimgoinghome]
   gamereload:
      usage: /gamereload
      description: Reload all games, effectively pissing everyone off.
   kit:
      usage: /kit <add/remove> <name>
      description: Admin commands to add and remove kits
   world:
      usage: /world <list/load/unload/teleport> [worldname]
      description: Load/Unload and teleport to worlds.
   tickets:
      usage: /tickets
      description: Look at all these tickets!
      aliases: [ticket, points, point, score]
   rewards:
      usage: /rewards
      description: See your unlocked rewards.
      aliases: [reward, perks, perk, menu, unlocked, unlocks]